Publish/#14
team-swith/swith-client pull request #15
Opened 2024-08-09 14:03 UTC by chaehyun-oh

## 📌 요약

> PR의 목적을 작성해주세요.

- close #14 

## 📝 작업 내용

-  스터디/팀원 탐색 공통 검색 컴포넌트
- 스터디 찾기 필터 (임시)
- 스터디 찾기 리스트
- 스터디 개별 카드

## 📚 참고

-

## 💖 리뷰 요구사항

-

## 🖥️ 스크린샷

2024-08-09 14:10 UTC, wontory requested changes
고생하셨습니다!
몇가지 궁금한 점과 수정했으면 하는 부분이 있어서 커멘트 남겨드려요!

2024-08-09 14:10 UTC, wontory commented on src/components/ui/card.tsx
현재는 Card 컴포넌트로 작업된 곳이 이 PR 한 개라서 상관 없겠지만,
공통 컴포넌트 수정은 다른 페이지의 스타일을 깨트릴 수 있어서
최대한 className으로 변경하거나 Button 컴포넌트처럼 variant를 만들면 좋을 것 같습니다!

2024-08-09 14:10 UTC, wontory commented on app/search/page.tsx
> +              </div>
태그가 현재 Chip으로 작업되어 있는데,
선택되어야하는 요소가 아니라면 Badge 컴포넌트를 제작해보시는건 어떤가요?

2024-08-09 14:10 UTC, wontory commented on app/search/page.tsx
page.tsx가 조금 긴 느낌이라 관심사별로 컴포넌트를 분리해주시면 좋을 것 같아요!

2024-08-09 14:12 UTC, wontory commented
PR 제목도 한번 더 신경써주시면 좋을것 같아요!! 👍🏻👍🏻

2024-08-10 12:30 UTC, chaehyun-oh commented on app/search/page.tsx
컴포넌트는 퍼블리싱 이후 기능 추가 시에 분리 할 예정입니다.

2024-08-11 09:59 UTC, SuaJeong-winter commented
확인했습니다!

2024-08-12 01:58 UTC, SuaJeong-winter approved these changes
확인했습니다

2024-08-12 01:59 UTC, merged